# Generated by Django 5.0.1 on 2024-01-28 06:40

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_projectmodel_last_activity_taskmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmodel",
            options={"verbose_name": "پروژه", "verbose_name_plural": "پروژه ها"},
        ),
        migrations.AlterModelOptions(
            name="taskmodel",
            options={"verbose_name": "کار", "verbose_name_plural": "کارها"},
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="date_added",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="for_date",
            field=django_jalali.db.models.jDateField(
                default=datetime.date(2024, 1, 28)
            ),
        ),
    ]
