# Generated by Django 5.0.1 on 2024-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[("a", "Awaiting"), ("d", "Done"), ("r", "ReDeclared")],
                default="a",
                max_length=1,
            ),
        ),
    ]
