# Generated by Django 5.0.1 on 2024-01-28 07:21

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_reminder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"verbose_name": "یادآور", "verbose_name_plural": "یادآورها"},
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("untill", django_jalali.db.models.jDateField(blank=True, null=True)),
                ("is_pinned", models.BooleanField()),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
